### ISSUE TITLE
Execute rho scan command with non-root user and request sudo password

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#122]
Currently rho supports scan with root and non-root users that can perform sudo without a password required.

This enhancement request is to allow sudo with password prompt.

ansible has a flag as part of running a playbook:
```
-K, --ask-become-pass                    ask for privilege escalation password
```
So we could use that option along with:
``` 
-b, --become                   run operations with become (does not imply password prompting)
```

Will need to see if any impact occurs to some of the raw tasks.

**Comment by noahl** [comment]
I talked with James Tanner, and there is a possible issue here. If we use `--ask-become-pass`, Ansible will prompt us for a single password for all hosts. If we want to support different passwords for different hosts, we need to put passwords in the inventory.

I think that different passwords for different hosts is an important feature. So I propose that I make sudo passwords an optional part of auths, and then use them when generating the inventory. It would mean that we would have to store users' sudo passwords, but multiple passwords seems like a must-have feature to me.

@chambridge @elyezer what do you think?

**Comment by chambridge** [comment]
@mdvickst Could you weigh in on what approach you feel `rho` needs?

**Comment by mdvickst** [comment]
I think that @noahl your approach is perfect. We should allow them to specify their sudo password as part of the auth so it's specific to each auth and is not prompting the user for each server. 

My question is what if the user's SSH password and the sudo password are the same? I can see this scenario being somewhat common but then how would we differentiate between using -K with the same password versus a separate sudo password? 

Maybe for now we just add a sudo_pass field to the auth which is optional. If it's provided then we use -K to run the playbook filling in that -K prompt with the sudo_pass field. It might be redundant for to have to enter your password twice but it matches the traditional workflow of input password to login and input sudo pass to elevate privileges.

**Comment by chambridge** [comment]
#206
