### ISSUE TITLE
Store profiles and auths in consistent location

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#136]
Right now, profiles and auths are stored in a `data` directory inside the current working directory of the user who runs rho. If the user changes their working directory, they lose their profile and auth information.

Based on http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/var.html, either `/var/local` or `/var/opt` would be appropriate places, depending on whether we decide to package rho inside `/usr/local` or `/opt`.

**Comment by elyezer** [comment]
Writing to those directories would require some additional permissions and maybe need to run rho using an user with some privileges. I would recommend taking a look on the XDG base directory specification [1], that we we could store configuration related files under `$HOME/.config/rho` and cache or data under `$HOME/.cache/rho`.

We can use the lib PyXDG (http://pyxdg.readthedocs.io) to help on grabbing the proper directories location.

[1] https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
