### ISSUE TITLE
Reset should be done automatically on all scans. A --cache flag should be provided to avoid the rediscovery flow.

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#138]
When running scan using a profile for the first time the command fails and require the user to re-run using the `--reset` option. See the output below:

```console
$ rho scan --reportfile report.csv --profile 1 --facts default
Please enter your rho vault password: 
Profile '1' has not been processed. Please use --reset with profile first.
```

I think that would be better if a question asking if the user wants to reset or reset was done automatically would be better instead of requiring the user to rerun the command adding the `--reset` option.

**Comment by chambridge** [comment]
Comment was made at demo meeting that we should instead alter the scan command to always function as it does with --reset and change it to instead  have a --no-reset command base on current SEAP usage.

I will update this issue to focus on that flow.
