### ISSUE TITLE
Avoid terminal overflow by truncating commands (tasks)

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#154]
Tasks like the redhat-packages command pull a lot of data that is sent to standard out. Look to see if its possible to truncate what is output per task so the terminal doesn't overflow with data but the user still see the updating progress of the scan.

**Comment by chambridge** [comment]
@mdvickst I am working on this feature and there are two things I'm doing

1. Limiting the number of lines per task that print out (useful if verbosity is high)
2. Limiting the length of a line output

Currently limiting to 5 lines for each task followed by:
**-- output truncated --**

Currently limiting line output to 100 characters.

All data is captured in the _scan_log_ file still.

Any feedback on output limitations would be appreciated.

Example output below:
```
PLAY [write facts first to a variable and then to csv locally] *****************

TASK [Gathering Facts] *********************************************************
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: christopherhambridge
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/christopherhambridge/.ansi
<127.0.0.1> PUT /var/folders/tr/w6c0zbvs0jzd25027nyyw06r0000gn/T/tmpZsdJ75 TO /Users/christop
-- output truncated --
TASK [write : store facts from all hosts in a variable] ************************
task path: /Users/christopherhambridge/Code/rho/roles/write/tasks/main.yml:3
ok: [localhost] => (item=10.10.181.175) => {
    "ansible_facts": {
        "host_fact": {
            "connection.host": "10.10.181.175", 
-- output truncated --
TASK [write : parse variable into a list of dictionaries] **********************
task path: /Users/christopherhambridge/Code/rho/roles/write/tasks/main.yml:8
ok: [localhost] => {
    "ansible_facts": {
        "host_facts": [
            {
-- output truncated --
TASK [write : write the list to a csv] *****************************************
task path: /Users/christopherhambridge/Code/rho/roles/write/tasks/main.yml:11
Using module file /Users/christopherhambridge/Code/rho/library/spit_results.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: christopherhambridge
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/christopherhambridge/.ansi
-- output truncated --
PLAY RECAP *********************************************************************
10.10.181.175              : ok=155  changed=70   unreachable=0    
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

**Comment by mdvickst** [comment]
@chambridge I like the idea of limiting each line to 100 chars, maybe we make that variable with the verbosity level? 100 chars for v, 200 for vv and so on?

Would it be possible to set a limit within each JSON object to 5 lines. What I mean is could we limit sterr and stout to 5 lines and a certain number of chars based on the verbosity level? I think those are the fields that are going to really add too much detail (specifically for the package query). Or maybe adjust this on the verbosity level as well, so for -v we limit stderr and stout to 1 line and then -vv is 2 lines etc.

Let me know what you think.

**Comment by chambridge** [comment]
👍 I like the approach!
