### ISSUE TITLE
Make RHO able to show its current version

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#161]
This repository offers an excellent issue template which will definitely help users submitting new issues. That said, it would be great if RHO offered an easy way to see its current version. For example, the python cli shows the current version by passing the `--version` option:

```console
$ python --version
Python 3.6.2
```

But RHO could provide the `rho version` command which is more aligned with its CLI design.

**Comment by chambridge** [comment]
It might be nice to collect some dependency information as well similar to what `ansible --version` does (i.e. also collects python version).

```
$ ansible --version
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```
