### ISSUE TITLE
rho auth edit does not fail when a not created auth entry is provided and there is no credentials created

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#165]
Trying to edit any field of a not created auth entry when there is no credentials created does not fail, see the output below.

```console
# Make sure there is no credentials created
$ rm -r data

# Try to edit a not created auth
$ rho auth edit --name=invalid --sshkeyfile path
Please enter your rho vault password: 
No auth credentials found
Auth 'invalid' updated

$ echo $?
0
```

The command fail properly when at least one other auth is created, see below:

```console
$ rm -r data

$ rho auth add --name 1 --username root --sshkeyfile path
Please enter your rho vault password: 

$ rho auth edit --name=invalid --sshkeyfile path
Please enter your rho vault password: 
Auth "invalid" does not exist

$ echo $?
1
```

## Type:
- Bug

### Bug severity:
- Low

**Comment by chambridge** [comment]
https://github.com/quipucords/rho/pull/170

**Comment by elyezer** [comment]
I have added a test to ensure this behavior https://github.com/quipucords/camayoc/commit/4840cc986143a1dad03ed77f1aaff71863c9db21
