### ISSUE TITLE
Provide similar output to both auth list and profile list when there is any entry created

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#179]
To be more concise, it would be good if both auth list and provided similar output. Currently auth list provides an message stating that there is no credentials created yet but profile list shows an empty list in JSON notation. See the output below:

```console
$ rho auth list       
Please enter your rho vault password: 
No credentials exist yet.

$ rho profile list    
Please enter your rho vault password: 
[]
```

It would be better if both followed the same pattern either providing a message or an empty list in JSON notation.

## Type:
- Enhancement

### Version of rho:
45775d8e82b9f35eb6c9dd75fb44a1430915b5ec

**Comment by chambridge** [comment]
@elyezer  I see the following when I try to reproduce. 
```
~/Code/rho$ ls data/
~/Code/rho$ rho auth list
Please enter your rho vault password: 
No credentials exist yet.
~/Code/rho$ rho profile list
Please enter your rho vault password: 
No profiles exist yet.
```

Can you provide insight to the state of your `data` directory at the time of execution?
