### ISSUE TITLE
Can't add a profile with custom SSH port

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#185]
Adding a profile with a custom ssh port is not working based on the output of show command. The profile should be added with the ssh port specified during the profile creation.

```console
$ rho profile add --name 2 --hosts 127.0.0.1 --auth 1 --sshport 5000
Please enter your rho vault password: 

$ rho profile show --name 2                                         
Please enter your rho vault password: 
{
    "auth": [
        {
            "id": "d4921fbf-438a-4e33-87dc-edb0a17d1940",
            "name": "1"
        }
    ],
    "hosts": [
        "127.0.0.1"
    ],
    "name": "2",
    "ssh_port": "22"
}
```

## Specify type:
- Bug

### Bug severity (if applicable):
- High

### Version of rho:
950c6acdbf618857409598721d3bd1ad5ff51757

**Comment by chambridge** [comment]
Side-effect of moving the port validation code up into the _validate_options method.

**Comment by elyezer** [comment]
This was raised by the automated test I have locally for that. So it seems that automation is starting to be valuable :tada:

**Comment by elyezer** [comment]
Ran the automation after pulling the changes and now it is back working.
