### ISSUE TITLE
Enable partial report generation

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#19]
Partial report generation (either periodic, or at ^C).
`rho` should write out the report occasionally so that if the tools need to be killed due to hanging, some amount of reporting would still be available.

https://github.com/candlepin/rho/issues/17

**Comment by mdvickst** [comment]
One option could be to also have a command to build a report from the log file. So if the program crashes rho 2.0 could still provide a report built from the log file that was being generated.

**Comment by chambridge** [comment]
Moved to sonar user story; closing this issue.
