### ISSUE TITLE
Eliminate use of Python in the ping module?

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#191]
Bug, severity low.

Probably not a big deal, but as far as I can tell we have one more use of Python on remote systems - when we make the ping inventory, Ansible sends a file called `ping.py` to the remote hosts and runs it, to verify that it can run remote Python code.

Since we don't want to use remote Python code, we should replace this with a raw ssh command running `echo "Hello world"` remotely, or something similar.

**Comment by noahl** [comment]
I called it low priority because I thought that surely `ping.py` didn't use any modern Python features, but in fact it has imports from `__future__`! (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/ping.py)

So this actually could potentially trip us up on old RHEL systems.

**Comment by mdvickst** [comment]
The JBoss Scanner currently works around this by looking for "pong" or specific error messages that may indicate a successful login but a possible python or other error. 

https://github.com/mdvickst/jboss-scanner/blob/master/build_ansible.py#L249
