### ISSUE TITLE
Masking of sensitive data in Rho reports

### ISSUE THREAD

**Issue by dozdowski** [quipucords/rho#196]
___

## Specify type:
- Enhancement
___

## Description:
The ability to disguise sensitive information in a report is valuable for security-conscious customers.  Certain items in Rho reporting could be considered useful reconnaissance for malicious entities, should they somehow acquire a report.

This feature should allow specific fact protection via option-flag input.

Minimal functionality would be exclusion of any fact from reporting, relying on user not to suppress obviously necessary items.  
Desirable functionality would be "masking" of facts, via forward encryption. 
Additional useful functionality would be enumeration of facts as either required in full or sensitive.

___

**Comment by dozdowski** [comment]
Further discussion with Mark V.

Simplest flow for coding, desired functionality, and flexibility with customer workflow is to add two new subcommands: redact and encrypt.  These subcommands would remain undocumented in user docs and the help subcommand to encourage normal reporting, but would allow revision of a rho report file to mask data that concerns customer security officers.

rho redact /path/to/rho-report.csv
This alters the 4 fields marked as sensitive by default and replaces them with a redaction string. (likely "redacted" to be obvious)

rho encrypt /path/to/rho-report.csv
This alters the 4 fields marked as sensitive by default and replaces them with a forward-encrypted hash, allowing the customer to share the key string and SEAP to verify the key string as needed.

The four sensitive by default facts are: connection.host, connection.port, uname.all, and uname.hostname

Each subcommand will include an undocumented --facts flag in case further data collected is interpreted as sensitive.  Specifying a fact or facts will result in encryption/redaction of the additional fact(s) or a response that the fact was not included in the report.

rho redact /path/to/rho-report.csv --facts cpu.bogomips
 -- Fact cpu.bogomips redacted

rho encrypt /path/to/rho-report.csv -- facts cpu.bogomips,dmi.bios-vendor,subman.virt.uuid
 -- Fact cpu.bogomips encrypted
 -- Fact dmi.bios-vendor encrypted
 -- Fact subman.virt.uuid was not present in /path/to/rho-report.csv

Specifying a sensitive by default flag inside a --facts option should have no effect on the behavior of the command (such as forward-encrypting by default and then forward-encrypting a SECOND time in response to the flag prompt)

**Comment by chambridge** [comment]
Going to also deliver an unecrypt capability so to simplify accessing the data.
