### ISSUE TITLE
Incorporate JBOSS scanner that gets information for JBOSS

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#20]
JBoss Scanner https://github.com/mdvickst/jboss-scanner

The focus of this issue is to pull in the scanning capabilities (not related to to the CLI UX).

**Comment by chambridge** [comment]
Below is a full list of what it currently can detect.
- JBoss EAP
- JBoss AS (community version of EAP)
- Wildfly (upstream project for EAP)
- JBoss A-MQ
- JBoss Fuse
- JBoss BRMS

**Comment by noahl** [comment]
This is closed by #53.

**Comment by noahl** [comment]
Current status is that all of the JBoss Scanner scanning code is in Rho. There could be bugs in specific parts of the scanner or how I imported it, but I think we should close this overall issue and track specific bugs in other issues as they come up.

**Comment by chambridge** [comment]
@noahl I think there is some more work left here in the integration.
- JBoss Facts should be collected as part of `default` (should be added to utilities.DEFAULT_FACTS_TUPLE with prefixes that make sense, i.e. jboss.eap.x etc.)
- JBoss Facts should be output to CSV. I see the roles run but nothing in the CSV output (even if its not finding associated products)
- JBoss Facts should be documented in [command syntax doc ](https://github.com/quipucords/rho/blob/master/doc/command_syntax_usage.rst#output)

**Comment by noahl** [comment]
@chambridge thanks for catching that! Those issues should all be fixed by #134 .
