### ISSUE TITLE
Verify Information Gathered Is Complete

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#21]
Verify Information Gathered Is Complete:
- **Red Hat Product Installed:** name of Red Hat family of product installed and version
- **Operating System Hostname:** hostname of the operating system reported
- **Physical/Virtual:** physical or virtual operating system
- **Physical Sockets:** number of sockets on the physical server (if applicable)
- **If Virtual, Number of vCPUs:** number of virtual cpus assigned to the virtual server
- **If Virtual, Hosted By:** hostname of the VMware Server running the RHEL VM reported
- **If Virtual, Sockets on Host:** number of physical sockets on the Vmware server
- **If Virtual, Host Cluster Name:** name of the VMware cluster
- **If Virtual, Number of Vmware Hosts in Cluster:** number of hosts in the cluster (if VMs are dynamically moved between hosts all hosts in the cluster must have a subscription)
- **Install Date:** date instance reported was installed
- **Number of Red Hat Packages:** detect how many packages have "redhat.com" in the build host that are not Fedora
- **UUID:** used to identify server in case of duplicates
- **Subnet:** IP and subnet mask of server to help identify dev vs prod for SLA

**Comment by chambridge** [comment]
I spoke with Chris Snyder to get an understanding of what existed in `rho 1.0` vs. any capabilities that could have been lost in `rho 2.0` vs. what he understands to be enhancements from the list above:

----
I would agree with your impression, the following I believe are enhancements:
- uuid (depending on the desired uuid, one could use the uuid gathered by subman)
- host cluster name
- number of vmware hosts in cluster
- virtual sockets


RHO does not have an install date although it can gather the details of the latest installed Red Hat package:
See the following facts: date.filesystem_create, date.machine_id, date.yum_history. While none of those directly answer the question of
when the system was installed, they can help to give an indication.

Regarding physical vs virtual sockets, I think it would be useful to distinguish between the two. Something like virt.cpu.socket_count.

It might be rather difficult to gather some of those VMware facts from inside a guest. I would suggest gathering those sort of facts from the VWware deployment directly (see virt-who github.com/virt-who/virt-who).

Bugs & enhancement issues are referenced above.

**Comment by chambridge** [comment]
@jlalbertson If you are fine with it, I would like to close this issue based on the investigation and discovery above and proceed by just tracking the issues associated above.

**Comment by jlalbertson** [comment]
@chambridge I am definitely ok with that. I think it makes sense to track the specific issues and not carry a large generic issue.
