### ISSUE TITLE
Can't specify a hostname as hosts option for profile commands

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#215]
## Specify type:
- Bug

### Bug severity (if applicable):
- Blocker ?
___

## Description:

One can't pass a hostname as the value for `--hosts` option:

```console
$ rho profile add --name 2 --hosts localhost --auth 1
Please enter your rho vault password: 
Bad host name/range : 'localhost'

$ rho profile add --name 2 --hosts elyezer.com --auth 1
Please enter your rho vault password: 
Bad host name/range : 'elyezer.com'

$ rho profile edit --name 1 --hosts localhost                           
Please enter your rho vault password: 
Bad host name/range : 'localhost'

$ rho profile edit --name 1 --hosts elyezer.com
Please enter your rho vault password: 
Bad host name/range : 'elyezer.com'
```

It also does not work when passing a list of hostnames:

```console
$ rho profile add --name 2 --hosts localhost elyezer.com --auth 1
Please enter your rho vault password: 
Bad host name/range : 'localhost'
```
___

### Version of rho:
```console
$ rho --version
version: 0.0.28
	ansible: 2.3.2.0
	python: 2.7.13 (default, Jun 26 2017, 10:20:05) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

**Comment by kdelee** [comment]
Ansible also supports using patterns in hostnames in an inventory file it is in the bottom of the ["hosts and groups" section in the inventory docs](http://docs.ansible.com/ansible/latest/intro_inventory.html#hosts-and-groups)

I think that since the functionality is allready in ansible, that rho *should* be able to leverage it.

I imagine it would work like this:
```
rho profile add --name 1 --hosts elijah[01:50].com --auth 1
```
Would add all 50 of those hosts using that auth.

**Comment by chambridge** [comment]
This should be an easy fix, just leftover regex code from the initial 2.0 branch that seems to have only focused on ip addresses/ranges.

**Comment by elyezer** [comment]
@chambridge maybe we could reuse the same validation and/or expansion function that ansible does.

**Comment by chambridge** [comment]
@elyezer Just need to change 
https://github.com/quipucords/rho/blob/master/rho/scancommand.py#L150
To handle more cases and then ansible will take care of the rest.
