### ISSUE TITLE
Can't collect some facts with sudo password

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#216]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:

Some facts can't be collected when sudo password is provided, for example using the following auth:

```console
$ rho auth show --name 1
Please enter your rho vault password: 
{
    "id": "b8b3258c-ca53-40c8-b4f4-4082a4e00499",
    "name": "1",
    "password": null,
    "ssh_key_file": "/home/elyezer/.ssh/id_rsa",
    "sudo_password": "********",
    "username": "sudopass"
}
```

The following facts are not being gathered:

```
cpu.socket_count: sudo: a password is required
date.anaconda_log: ls: cannot access /root/anaconda-ks.cfg: Permission denied
date.yum_history: You don't have access to the history DB.
```

On an user without sudo password the following facts can't be gathered:

```
date.anaconda_log: ls: cannot access /root/anaconda-ks.cfg: Permission denied
date.yum_history: You don't have access to the history DB.
```

All facts are properly gathered when using the root user.
___

### Version of rho:

```console
$ rho --version
version: 0.0.28
	ansible: 2.3.2.0
	python: 2.7.13 (default, Jun 26 2017, 10:20:05) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

**Comment by chambridge** [comment]
I think this is the same work as #207 that Noah was going to look at.

**Comment by elyezer** [comment]
Yeah, those facts are not specific to subman but the fix for the subman should be the same for this issue.

**Comment by noahl** [comment]
@elyezer thanks for the report! I will work on this along with #207 .
