### ISSUE TITLE
Should check for command existence before trying to run it?

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#217]
## Specify type:
- Enhancement
___

## Description:

On the generated scan report some facts shows like:

date.filesystem_create | virt.num_guests | virt.num_running_guests
-- | -- | --
bash: tune2fs: command not found | bash: virsh: command not found | bash: virsh: command not found

Do you think it would be better to try to check for some those non-standard commands and if they don't exist print another message or leave it blank like the `jobss.*` facts?

___

### Version of rho:
```console
$ rho --version
version: 0.0.28
	ansible: 2.3.2.0
	python: 2.7.13 (default, Jun 26 2017, 10:20:05) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

**Comment by chambridge** [comment]
@elyezer I actually prefer getting an error like the above over leaving thing blank as it shows that something was at least run. 

But I'm open to other opinions as well.

**Comment by elyezer** [comment]
@chambridge it makes sense and I agree that those error messages are better than a blank value. Also, it does not make sense to do additional processing to replace those messages to something else that will say the same thing.

Maybe we could improve the jboss related facts stating something like `N/A`, it seems that a blank field does not provide enough information after thinking about this one more time.

**Comment by chambridge** [comment]
@elyezer Yep, I agree that would be nicer.

**Comment by noahl** [comment]
I was talking with @chambridge and he says that he also wants error messages (and non-blank output) when we scan for things and they are not found. I'll leave this issue open for that.

**Comment by noahl** [comment]
I think https://github.com/quipucords/rho/pull/296 handled this for the jboss case. Leaving this open because I think there are still come commands that can give blank output.

**Comment by noahl** [comment]
This issue has become a catch-all for a bunch of different, separate work items. I'd like to close this for now, and file issues for specific commands not producing output if and when that comes up.

@chambridge please reopen if you disagree.
