### ISSUE TITLE
Add rho encrypt capability

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#220]
## Specify type:
- Enhancement
___

## Description:

Simplest flow for coding, desired functionality, and flexibility with customer workflow is to add a new subcommand: encrypt. encrypt would allow revision of a rho report file to mask data that concerns customer security officers.

`rho encrypt /path/to/rho-report.csv`
This alters the 4 fields marked as sensitive by default and replaces them with a forward-encrypted hash, allowing the customer to share the key string and SEAP to verify the key string as needed.

The four sensitive by default facts are: connection.host, connection.port, uname.all, and uname.hostname

```
rho encrypt /path/to/rho-report.csv -- facts cpu.bogomips,dmi.bios-vendor,subman.virt.uuid
-- Fact cpu.bogomips encrypted
-- Fact dmi.bios-vendor encrypted
-- Fact subman.virt.uuid was not present in /path/to/rho-report.csv
```

Associated with #196

**Comment by mdvickst** [comment]
I had envisioned this being an MD5 hash since that is easy for us to replicate and therefore compare to values from other data sources (vCenter, RHSM, Satellite etc.). I like that this method can be decrypted using Ansible vault but I'm struggling to find a way that we could easily replicate this encryption for other data sources for comparison of common records.

**Comment by chambridge** [comment]
@mdvickst So you didn't really want "encryption" you wanted hashing of the data.

I can change `rho fact encrypt` to just do the following:
```
import hashlib

def computeMD5hash(string):
    m = hashlib.md5()
    m.update(string.encode('utf-8'))
    return m.hexdigest()
```
But obviously I will have to remove `rho fact decrypt`

**Comment by mdvickst** [comment]
@chambridge 

Yes I guess hashing would be the correct term here for what we are looking for. I guess an encrypted value is fine too but the Ansible vault output is a little bit cumbersome for comparison. The goal of the customers is to mask their sensitive data so it can't be reversed and our goal is to be able to still compare that across records from other sources to eliminate duplicates. 

I think just using hashlib.md5 and removing encrypt would work. Maybe we should rename "rho fact encrypt" to "rho fact mask"?

**Comment by chambridge** [comment]
@elyezer FYI to the changes above. I know you've begun automating. I'll try and make these updates as soon as possible.

**Comment by elyezer** [comment]
After the last comments I am wondering if redact still useful. Like if I can hash some facts why I would remove them?

@mdvickst do you think even with the hashing in place the redact (removal of facts) still necessary?

**Comment by elyezer** [comment]
> @elyezer FYI to the changes above. I know you've begun automating. I'll try and make these updates as soon as possible.

@chambridge no worries, I am aware that we are going to need updating the tests until we get closer to a stabilized API

**Comment by mdvickst** [comment]
@chambridge @elyezer I agree redact is not necessary. If it is really desired anyone could just remove the columns from the CSV file. Having a redact option might lead people to removing facts when they normally would not have done so.
