### ISSUE TITLE
Travis not failing builds when Python 3 tests fail

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#222]
For instance, https://travis-ci.org/quipucords/rho/jobs/268149673 should have been a failure, but wasn't.

I don't know what part of the system is causing the error yet.

**Comment by chambridge** [comment]
I have resolved this issue with the following commit:
https://github.com/quipucords/rho/pull/240/commits/2453ab8c043dee79897a9a27f2e9897bad63c226
