### ISSUE TITLE
test_clicommands.py breaks in Python 3

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#223]
The issue seems to be in

```
            with open(TMP_TEST_REPORT_SENSITIVE, 'wb') as data_temp:
                writer = csv.DictWriter(data_temp,
                                        fieldnames=sorted(report_keys),
                                        delimiter=',')

                # Write a CSV header if necessary
                writer.writeheader()
```

in Python 3, a file opened in mode `wb` will raise an exception when `.write()` is passed a `str`. It needs to be opened as `w` instead.

**Comment by noahl** [comment]
@chambridge @jlalbertson @elyezer do we care about Windows support for the controller?

I have some code that fixes this by adding a function to `utilities` that opens the file with `wb` in Python 2 and `w` in Python 3. But if we don't support Windows on the controller, then it would be simpler to just use `w` everywhere.

I would prefer not to try to support Windows controllers right now, since we don't have a way to test them anyway. If customers ask for it, it shouldn't be too hard to go back and do it the other way.

**Comment by elyezer** [comment]
> I would prefer not to try to support Windows controllers right now, since we don't have a way to test them anyway. If customers ask for it, it shouldn't be too hard to go back and do it the other way.

I think the focus right now is Linux as controller so it makes sense to not worry much about Windows.

**Comment by noahl** [comment]
@elyezer I agree. I will send out a PR to fix this by changing `wb`/`rb` to `w` and `r`, respectively. It is easy to have Rho choose at runtime, if necessary, but I'd rather not add another layer of indirection unless we need it.
