### ISSUE TITLE
User may encounter python bug

### ISSUE THREAD

**Issue by kdelee** [quipucords/rho#227]
# User may encounter python bug
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
Users may encounter a bug in python while running scan command.
See related [ansible bug report](https://github.com/ansible/ansible/issues/21982) and the [actual bug report on the python bug tracker](https://bugs.python.org/issue29519):
___

### Version of rho:
```
$ rho --version
version: 0.0.28
	ansible: 2.3.2.0
	python: 3.5.3 (default, May 10 2017, 15:05:55) 
```

### Expected behavior:
Running `rho scan --profile myprofile --reportfile out.csv` should run without spewing lots of errors.

### Actual behavior:
Running `rho scan --profile myprofile --reportfile out.csv`  spews lots of errors much like:

```
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f87daad5510>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

### Steps to reproduce:
Install rho in a Python 3.5.3 environment. (This bug probably effects other python versions too -- see [python bug tracker](https://bugs.python.org/issue29519) )

Create an auth and profile pointing to a valid host, and run scan on that host.

```
$ python3.5 -m venv rho-env
$ source rho-env/bin/activate
$ git clone https://github.com/quipucords/rho.git
$ cd rho
$ pip install -r requirements.txt
$ rho auth add --name muskmelon --sshkeyfile=/home/elijah/.ssh/id_rsa --username root
$ rho profile add --name muskmelon --hosts XXX.XXX.XXX.XXX --auth muskmelon
$ rho scan --profile muskmelon  --reportfile out.csv
... lots of errors but tasks all run and report is generated ...
```

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora             | 25        | 3.5.3            | bare metal
Target System   | RHEL             | 7.3        | 2.7.5          | libvirt

### Proposed solution:

This is not a bug in rho, this is a bug in certain versions of Python (all affected versions not yet determined). Documentation should advise users that if they encounter this bug, they may want to install a newer version of python, or other work around. This does not effect the return code, the errors are ignored, so it should not affect scripting. Simply may worry user.

**Comment by noahl** [comment]
I don't understand why we are encountering this. The upstream bug says it's connected to multiprocessing, but I don't think we use that module anywhere. I've also never seen this behavior, even though the upstream bug mentions Python 3.6 (which is what I'm using). @kdelee how many hosts are in your profile?

**Comment by kdelee** [comment]
It was just that one host I show in the "Steps to Reproduce"

**Comment by kdelee** [comment]
Just created fresh environment to try again with this same host/profile set up. 

It looks like all the ansible tasks are no longer being written to stdout, so this behaviour is not visible any more, even if it _maybe_ is happening. So this is not showing up for me at `commit 9b5253dcaae233803dbba4084705be3528512b43`

I could try and walk back a few commits and see when it re-appears.

**Comment by noahl** [comment]
Oh, that makes sense.

I was worried about showing error messages to users, but given that it's not visible by default, I would feel safe letting the Python fix propagate to user systems and not trying to do more on our end right now. @chambridge what do you think?

**Comment by chambridge** [comment]
I'm good with that, but I'm concerned about the statement above:

> It looks like all the ansible tasks are no longer being written to stdout

@kdelee you should see output from the ansible playbook being output to the console and it should be going to a log in `~/.local/share/rho`.

**Comment by kdelee** [comment]
@chambridge 
Ok ran it again and I checked out the `~/.local/shar/rho/scan_log`, I am not seeing the errors.

~~Still curious to see if it something that changed in rho, or the other possibility is I updated may have updated very python version that was creating this bug in the first place 🤒~~

Seems like it is still the same python:
```
rho --version
version: 0.0.28
	ansible: 2.3.2.0
	python: 3.5.3 (default, May 10 2017, 15:05:55) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

**Comment by chambridge** [comment]
Ok. I'm going to close then. Feel free to reopen if you encounter this again.
