### ISSUE TITLE
Checking input for --hosts

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#239]
# Openning a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
Provide a description of the issue being raised.
Rho allows users to input CIDR format for hosts but ansible does not understand that notation.
```
[root@rho-scanner yum.repos.d]# rho profile edit --name local_hosts1 --auth root1 --hosts 192.168.124.0/24
Please enter your rho vault password: 
Profile 'local_hosts1' edited
[root@rho-scanner yum.repos.d]# rho profile list
Please enter your rho vault password: 
[
    {
        "auth": [
            {
                "id": "f7da68f9-c0c3-4054-a344-a3e2c7d54947",
                "name": "root1"
            }
        ],
        "hosts": [
            "192.168.124.0/24"
        ],
        "name": "local_hosts1",
        "ssh_port": "22"
    }
]
```

___

### Version of rho:
[ 0.27, 0.28 ]

### Expected behavior:
Describe the expected behavior for the program.
Ideally rho should allow this type of input and then convert it to ansible acceptable format. 

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.
[root@rho-scanner yum.repos.d]# rho profile edit --name local_hosts1 --auth root1 --hosts 192.168.124.0/24
### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.3       | 2.7.5          | KVM

**Comment by chambridge** [comment]
I intend to fix the bug that should not allow this form of input, by correcting the regex processing.
```
~/Code/rho$ rho profile add --name=local_hosts7 --auth vmware --hosts 192.168.124.0/25
Please enter your rho vault password: 
Bad host name/range : '192.168.124.0/25'
```

Please open a separate enhancement to add support for CIDR style format as currently we only handle what ansible will handle and don't perform and transformations.
