### ISSUE TITLE
--sudo-password requires --password option

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#244]
# Openning a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Low
___

## Description:
when creating a new auth profile if you use --sudo-password option you also have to specify --password. If not using --sudo-password it will automatically prompt for ssh connection password even if the --password option is not specified. 
___

### Version of rho:
[ 0.27, 0.28 ]

### Expected behavior:
Either always require --password or imply that if --sshkeyfile option is not specified need to prompt for connection password, regardless of if --sudo-password option is used. 

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
```
[mvickstr@mvickstr-fedora ~]$ rho auth add --name mvickstr-sudo1 --user mvickstr --sudo-password 
Usage: rho auth add [options]

adds the authorization credentials to the config

Options:
  -h, --help            show this help message and exit
  -v                    Verbose mode. Use up to -vvvv for more verbosity.
  --name=NAME           auth credential name - REQUIRED
  --sshkeyfile=FILENAME
                        file containing SSH key
  --username=USERNAME   user name for authenticating against target machine -
                        REQUIRED
  --password            password for authenticating against target machine
  --sudo-password       password for running sudo
  --vault=VAULT         file containing vault password for scripting
[mvickstr@mvickstr-fedora ~]$ rho auth add --name mvickstr-sudo1 --user mvickstr --sudo-password --password
Please enter your rho vault password: 
Provide connection password.
Password: 
Provide password for sudo.
Password: 
Auth "mvickstr-sudo1" was added
```

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by noahl** [comment]
@mdvickst I think the current behavior is correct. The sudo password is only used to increase privileges once rho has logged into the machine it's scanning. In the first example you gave, where `sudo-password` was the only authentication flag, rho would have no way to log into the machine in order to use the sudo password. However, you should be able to specify a sudo password with either username+password authentication or username+ssh key file.

Is there a documentation bug here about the option description being unclear?

**Comment by mdvickst** [comment]
@noahl I agree with you that the behavior is correct, however my point is more from a usability perspective. It''s confusing that --password does not have the provided as part of the command all the time. 

If you are not using the --sudo-password option you are not required to provide the --password option, it will still prompt you to enter the connection password even if --password is not specified. If using --sudo-password it --password is no longer optional.

**Comment by chambridge** [comment]
@mdvickst We didn't assume here that the connection password == the sudo-password. We allow connection with one password and sudo with another currently.

Logic right now is:
--name is REQUIRED
--username is REQUIRED
either --password or --sshkefile is REQUIRED
--sudo-password is optional and no flag is dependent on it.

**Comment by mdvickst** [comment]
I've just tested this on rho-0.0.28-1.git.232.cb5da5e.fc26.noarch and that logic of "either --password or --sshkefile is REQUIRED" works. What maybe wasn't clear in my original comment was that `rho auth add --name mvickstr-sudo1 --user mvickstr ` was working as well in a previous version. I'm going to go ahead and close this out.
