### ISSUE TITLE
JBoss scanner appears to not work in current master

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#255]
I just ran a test JBoss scan from master. I can see in the log that Rho collected the information it needed, but it didn't make it to the output file.

**Comment by noahl** [comment]
@chambridge tells me it's working for him, so this may be something specific to my setup. I think that makes this low priority compared to the Sprint 5 stuff, so I will work on other issues for now.

**Comment by chambridge** [comment]
Let's close this for now and reopen if you continue to see this issue with a clean environment.
