### ISSUE TITLE
JBoss Scanning Takes Long time on Large Filesystems

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#273]
# Openning a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- High
___

## Description:
When the Jboss scanner tasks that use a 'find' command run on large filesystems the commands take a long time to complete (sometimes days) causing the script to appear hung.
___

### Version of rho:
ALL

### Environment information:
Target filesytem was NFS and below is the size and path.

> ipxnas03.midwestiso.org:/sysdeploy
>                       6.9T  5.2T  1.8T  75% /sysdeploy

**Comment by mdvickst** [comment]
Possible solutions so far discussed

- Using -xdev with Find
- Using locate command (if installed)
- limiting Rho 2.0 to filesystems under a certain size
- tiered approach

**Comment by mdvickst** [comment]
I have tested scanning an NFS filesystem with EAP 7.0 in the share mounted on /jboss and when the -xdev option is used that directory is not scanned. 

Below if the commands I used. 

FOUND=""; for jar in `find / -xdev -name 'jboss-modules.jar' 2>/dev/null | grep -v '\.installation/patches'`; do VERSION=$(java -jar ${jar} -version 2> /dev/null | grep version | sed 's/.*version\s//g'); inode=$(stat -c '%i' "${jar}"); fs=$(df  -T "${jar}" | grep "/dev" | sed 's/ .*//'); ctime=$(stat ${jar} | grep 'Change' | grep -oP '[1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]'); if [ ! -z "${VERSION}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $VERSION**$ctime"; else FOUND=${VERSION}'**'${ctime}; fi; fi; done; echo ${FOUND}

FOUND=""; for jar in `find / -xdev -name 'run.jar' 2>/dev/null`; do VERSION=$(java -jar ${jar} --version 2> /dev/null | grep build  | sed 's/.*[CS]V[NS]Tag.//g' | sed 's/\sdate.*//g'); inode=$(stat -c '%i' "${jar}"); fs=$(df  -T "${jar}" | tail -1 | sed 's/ .*//'); ctime=$(stat ${jar} | grep 'Change' | grep -oP '[1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]'); if [ ! -z "${VERSION}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $VERSION**${ctime}"; else FOUND=${VERSION}'**'${ctime}; fi; fi; done; echo ${FOUND};

**Comment by chambridge** [comment]
@mdvickst I'm going to separate this enhancement into multiple enhancements as the possible solutions mentioned above can be tackled separately but individual add improvements.

**Comment by chambridge** [comment]
Opened individual enhancements. Closing this larger one.
