### ISSUE TITLE
JBoss Scanner does not return path of EAP if Java is not installed

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#274]
# Openning a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Low
___

## Description:
If java is not installed on the scanning system the two tasks for detecting EAP will not complete successfully and will not display EAP installation if they are present. EAP runs on Java so I don't expect this to be very common but worth documenting.

**Comment by chambridge** [comment]
Any thoughts on where we should document this item? I was thinking here:
https://github.com/quipucords/rho/blob/master/doc/command_syntax_usage.rst#programs-on-remote-machines

But I'm open to creating some kind of FAQ or Troubleshooting doc linked off the README as well.

**Comment by chambridge** [comment]
I'm going to create a **FAQ** doc for the above:

@kdelee You may want to put your content for #288 in the FAQ doc as well.
