### ISSUE TITLE
Sanitize --scan-dirs input for valid directory format

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#275]
## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
The input to the --scan-dirs option on a scan should verify that the input is of the appropriate format.
___

### Version of rho:
0.28

### Expected behavior:
Only accept valid path formats for input to --scan-dirs. Provide an error if the format is not valid.

### Actual behavior:
No checking of input data is provided

### Steps to reproduce:
Execute the scan command with the --scan-dirs option with invalid data.

**Comment by chambridge** [comment]
Basically looking to test the input values with `os.path.isabs(PATH)` since the given paths are expected to be for a remote system, this is about all we can test.

**Comment by elyezer** [comment]
Another option is to use shlex.quote [1] or something equivalent on Ansible.

Also the playbook can check if the list of paths are valid before proceeding, that way it will ensure the path exists on the remote system.

[1] https://docs.python.org/3.5/library/shlex.html#shlex.quote
