### ISSUE TITLE
JBoss scanning should use -xdev when running the find command

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#289]
## Specify type:
- Enhancement
___

## Description:
When the Jboss scanner tasks that use a 'find' command run on large filesystems the commands take a long time to complete (sometimes days) causing the script to appear hung.

Related to #273
___

### Version of rho:
ALL

### Environment information:
Target filesytem was NFS and below is the size and path.

> ipxnas03.midwestiso.org:/sysdeploy
>                       6.9T  5.2T  1.8T  75% /sysdeploy

___

I have tested scanning an NFS filesystem with EAP 7.0 in the share mounted on /jboss and when the -xdev option is used that directory is not scanned. 

Below if the commands I used. 
```
FOUND=""; for jar in `find / -xdev -name 'jboss-modules.jar' 2>/dev/null | grep -v '\.installation/patches'`; do VERSION=$(java -jar ${jar} -version 2> /dev/null | grep version | sed 's/.*version\s//g'); inode=$(stat -c '%i' "${jar}"); fs=$(df  -T "${jar}" | grep "/dev" | sed 's/ .*//'); ctime=$(stat ${jar} | grep 'Change' | grep -oP '[1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]'); if [ ! -z "${VERSION}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $VERSION**$ctime"; else FOUND=${VERSION}'**'${ctime}; fi; fi; done; echo ${FOUND}

FOUND=""; for jar in `find / -xdev -name 'run.jar' 2>/dev/null`; do VERSION=$(java -jar ${jar} --version 2> /dev/null | grep build  | sed 's/.*[CS]V[NS]Tag.//g' | sed 's/\sdate.*//g'); inode=$(stat -c '%i' "${jar}"); fs=$(df  -T "${jar}" | tail -1 | sed 's/ .*//'); ctime=$(stat ${jar} | grep 'Change' | grep -oP '[1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]'); if [ ! -z "${VERSION}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $VERSION**${ctime}"; else FOUND=${VERSION}'**'${ctime}; fi; fi; done; echo ${FOUND};
```

**Comment by chambridge** [comment]
@mdvickst

Seems like this is a simple update to just add the `-xdev` flag to tasks where we are performing the find command, or am I missing something else here?

**Comment by mdvickst** [comment]
Yes, I added this to the JBoss scanner last week but today I had feedback that a customer is running JBoss in `/opt` which is a separate filesystem for them. 

I think we should still use `-xdev` but may include some of the common directories in the find command in case they are on separate filesystems. 

E.g.
```
FOUND=""; for jar in `find / /opt /app -xdev -name 'jboss-modules.jar' 2>/dev/null | grep -v '\.installation/patches'`; do VERSION=$(java -jar ${jar} -version 2> /dev/null | grep version | sed 's/.*version\s//g'); inode=$(stat -c '%i' "${jar}"); fs=$(df  -T "${jar}" | grep "/dev" | sed 's/ .*//'); ctime=$(stat ${jar} | grep 'Change' | grep -oP '[1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]'); if [ ! -z "${VERSION}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $VERSION**$ctime"; else FOUND=${VERSION}'**'${ctime}; fi; fi; done; echo ${FOUND}
```

**Comment by chambridge** [comment]
@mdvickst Ok. To sum up we can add the `-xdev` option to the `find` commands, but when we do we should expand our default for the `--scan-dirs` option to be `['/', '/opt', '/app']`.
Sound good?

**Comment by mdvickst** [comment]
Yes that makes sense. On second thought, let's include a few more to be
safe.
['/', '/opt', '/app', '/home', '/usr']
