### ISSUE TITLE
Collect Current Subscription Attached through Subscription-Manager

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#299]
# Openning a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Low
___

## Description:
It would be helpful to pull the current subscription SKU(s) and subscription name(s) from subscription manager if the server is registered and has 1 or more subscriptions attached. This information is useful to determine SLA and intended subscription that customers have applied (e.g. if a Premium JBoss EAP subscription has been applied we should expect to find EAP jars installed and that the customer expects premium SLA. 
___

**Comment by chambridge** [comment]
@mdvickst Would the following capture what you are looking for?

```
$ subscription-manager list --consumed | grep '^SKU:' | sed  -n -e 's/^.*SKU\s*.\s*//p'
ESA0001
ESA0009
```

If so I could create a `subman.consumed` fact with a list of SKUs consumed.

**Comment by mdvickst** [comment]
This makes sense. For added clarity could we add the "Subscription Name" as well?

Example "Employee Subscription - ES0113909"

**Comment by chambridge** [comment]
Yep, sorry missed that part:
```
$ subscription-manager list --consumed | grep -e '^SKU' -e '^Subscription Name' | sed -n -e 's/SKU\s*.\s*//p' -e 's/Subscription Name\s*.\s*//p' | awk '{ ORS = (NR%2 ? " - " : RS) } 1'
Red Hat Enterprise Linux, Company-Wide Subscription (Pilot) - ESA0001
Red Hat JBoss Fuse, Company-Wide Subscription (Pilot) - ESA0009
```

**Comment by mdvickst** [comment]
LGTM!
