### ISSUE TITLE
Improve README documentation

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#3]
Improve information format for `rho 2.0`, provide more developmentinformation to easy on-boarding:

- [x] Introduction
- [x] CLI Command reference
- [x] Development Setup
- [x] Testing

**Comment by chambridge** [comment]
@jlalbertson 
Should we update the contact info adding Noah & myself to the 2.0 version?
https://github.com/quipucords/rho/tree/issues/3#contact

I assume the bug reporting information should stay the same?
https://github.com/quipucords/rho/tree/issues/3#known-issues

Are we planning on providing the same installation flow?
https://github.com/quipucords/rho/tree/issues/3#installation

**Comment by jlalbertson** [comment]
@chambridge Yes - update the contact information for 2.0 for Noah and yourself

For the other two - let's discuss with the team

**Comment by chambridge** [comment]
Thanks, I've opened the following issues to track these separate decisions. We can alter the README if necessary once we've closed on these issues.

https://github.com/quipucords/rho/issues/24
https://github.com/quipucords/rho/issues/25
