### ISSUE TITLE
Collect product certificates that are installed

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#300]
# Openning a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Low
___

## Description:
Collect a fact which contains all of the product certificate names installed in the /etc/pki/product/ directory. E.g. "69.pem, 83.pem" would indicate that this is a RHEL Server with High Availability installed. 
___

**Comment by chambridge** [comment]
@mdvickst Would the following capture what you are looking for?
```
$ ls /etc/pki/product/ | grep ".pem"
183.pem
230.pem
251.pem
```
If so I could create a fact `redhat-packages.certs` with the list of cert files.

**Comment by mdvickst** [comment]
That's perfect.
