### ISSUE TITLE
Move man page to different format

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#301]
After looking at our man page, the current format (troff?) seems unnecessarily difficult to actually write in. I suggest that we move to a different format and use pandoc (https://pandoc.org/) to convert to troff for the man page.

Another advantage would be that if we had the man page in a different format, it would be easier to convert to HTML for use in a hypothetical Sonar web interface.

I think Markdown and reStructuredText would be good formats, but there are plenty of options. I'm bringing this up now so that if we decide to go to a different format, Jamie won't have to suffer with troff.

@chambridge what do you think?

**Comment by chambridge** [comment]
I don't have a problem with this, just comes down to how many cycles this would take.
