### ISSUE TITLE
If one host in profile with multiple hosts is unreachable, no error or message is generated

### ISSUE THREAD

**Issue by kdelee** [quipucords/rho#302]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
If a profile is scanned that contains at least one valid host, the scan completes with no complaints, even if there were unreachable hosts in the profile.
___

### Version of rho:
```
version: 0.0.28
	ansible: 2.3.2.0
	python: 3.6.2 (default, Jul 24 2017, 14:22:34) 
```

### Expected behavior:
While I think it is good that rho goes on and scans the reachable systems, I think it should say *something* about the fact there were unreachable hosts.

This can be a hair-pulling bug if you are scanning lots of systems and are trying to figure out why your report contains less rows than you have hosts in the profile.

### Actual behavior:
If at least one host is reachable, the scan completes with no complaints and generates a report file with only information pertaining to the reachable hosts.

### Steps to reproduce:
0) Create an auth for a system you have access to and is alive
1) Create a profile with at least one valid host and one invalid host and the auth that will grant you access to the valid host.
2) Run a scan against that profile.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora             | 25        | 3.6            | Bare Metal
Target System   | RHEL             | 7.4        | 2.7.5          | ESXi
Target System   | Invalid Host             | --       | --          | --

**Comment by kdelee** [comment]
FYI tests for this type of behaviour is included in some of the scan tests I am working on that use camayoc against remote systems. I will be making a PR later this week.

Also, to be clear, rho does fail the scan if ALL hosts are invalid. This only occurs when there is at least one valid host.

**Comment by chambridge** [comment]
We need to think through more variations for user output here.

What happens if you give an ip range? We wouldn't want to output all ips that we couldn't connect to. So we are saying we only want to do it for those that were precisely specified in the profile.

I definitely agree user feedback could be improved here, but I'd also argue this maybe considered an enhancement. One worth doing if we can decide the right data to provide back.

**Comment by kdelee** [comment]
I see where you are coming from with the ip range. 

I do think it is in fact a nice feature that the scan goes on even if all hosts are not reachable, I just think there needs to be some indication of this. I know ansible, somewhere down in there, is letting us know which hosts were unreachable.

**Comment by chambridge** [comment]
Yep, we definitely have an idea of what was unreachable. But what should we be reporting to the user. 

One suggestion is we could provide a summary after the "discovery process", see example:
```
57 hosts are reachable and will be scanned. 4 hosts were unreachable and will not be scanned; for further information see $XDG_DATA_HOME/rho/unreachable_hosts
```

**Comment by kdelee** [comment]
That looks great :+1:

On Sep 14, 2017 9:26 AM, "Chris Hambridge" <notifications@github.com> wrote:

Yep, we definitely have an idea of what was unreachable. But what should we
be reporting to the user.

One suggestion is we could provide a summary after the "discovery process",
see example:

57 hosts are reachable and will be scanned. 4 hosts were unreachable
and will not be scanned; for further information see
$XDG_DATA_HOME/rho/unreachable_hosts_lo


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quipucords/rho/issues/302#issuecomment-329480927>, or mute
the thread
