### ISSUE TITLE
Dash in Hosts range throws exception

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#304]
# Openning a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High

___

## Description:
Using a "-" instead of ":" in the hosts range throws exception. 
___

### Version of rho:
0.28

### Expected behavior:
Rho should reject command and provide feedback to the user on the error. 

### Actual behavior:
Traceback (most recent call last):
  File "/usr/bin/rho", line 28, in <module>
    CLI().main()
  File "/usr/lib/python2.7/site-packages/rho/cli.py", line 137, in main
    cmd.main()
  File "/usr/lib/python2.7/site-packages/rho/clicommand.py", line 87, in main
    self._do_command()
  File "/usr/lib/python2.7/site-packages/rho/profileaddcommand.py", line 131, in _do_command
    range_list = read_ranges(self.options.hosts)
  File "/usr/lib/python2.7/site-packages/rho/utilities.py", line 322, in read_ranges
    "no such file", reg_item))
TypeError: ugettext() takes exactly 2 arguments (3 given)
[mvickstr@mvickstr-fedora rho]$ 

### Steps to reproduce:
[mvickstr@mvickstr-fedora rho]$ rho profile add --name test-dash --hosts 192.168.124.[1-254] --auth test
Please enter your rho vault password: 
[mvickstr@mvickstr-fedora rho]$ rho profile add --name test-dash2 --hosts 192.168.[1-2].[1:254] --auth test
Please enter your rho vault password: 
Traceback (most recent call last):
  File "/usr/bin/rho", line 28, in <module>
    CLI().main()
  File "/usr/lib/python2.7/site-packages/rho/cli.py", line 137, in main
    cmd.main()
  File "/usr/lib/python2.7/site-packages/rho/clicommand.py", line 87, in main
    self._do_command()
  File "/usr/lib/python2.7/site-packages/rho/profileaddcommand.py", line 131, in _do_command
    range_list = read_ranges(self.options.hosts)
  File "/usr/lib/python2.7/site-packages/rho/utilities.py", line 322, in read_ranges
    "no such file", reg_item))
TypeError: ugettext() takes exactly 2 arguments (3 given)

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by elyezer** [comment]
This diff fixes the issue:

```diff
diff --git a/rho/utilities.py b/rho/utilities.py
index 73730f4..6ddec35 100644
--- a/rho/utilities.py
+++ b/rho/utilities.py
@@ -319,7 +319,7 @@ def read_ranges(ranges_or_path):
             logging.error(_("Bad host name/range : '%s'"), reg_item)
             if len(range_list) <= 1:
                 logging.error(_("Couldn't interpret %s as host file because "
-                                "no such file", reg_item))
+                                "no such file"), reg_item)
 
             sys.exit(1)
```

**Comment by elyezer** [comment]
I think a message could also be added. Currently it just fail returning a non-zero return code as expected.

**Comment by elyezer** [comment]
@mdvickst do you expect that the ranges should also accept the `-` as a range indicator or should it fail and only accept `:`?

**Comment by mdvickst** [comment]
@elyezer I think it would be a nice UX enhancement to support "-" instead of just ":". I think users try to do this from memory or don't read the docs closely and this could potentially trip them up, plus I think it would be easy to just swap out the two characters when it's being read in. That being said it's not critical as long as there is a meaningful error message.

**Comment by chambridge** [comment]
FYI @elyezer I believe anything going to `logging.error()` will be output to the user per @noahl change here: https://github.com/quipucords/rho/blob/master/rho/utilities.py#L174

However, the message would not be super in this case.

**Comment by elyezer** [comment]
@chambridge I will try one more time, I did not see it when I run or maybe I just missed it. Better to double check. Thanks for the heads up.

**Comment by chambridge** [comment]
@elyezer Tried it this morning. No error message for me so what was added here doesn't work for `cidr_to_ansible()` method either. I'll dive a bit deeper.
