### ISSUE TITLE
Scanning a subset of all facts may cause the scan command to not generate the report file

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#312]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:

Running `rho scan` and passing a subset of facts may cause the command to not generate the report file and to not return a non-zero exit code.
___

### Version of rho:
1d553b58e006b3c39e678ccaca95473ff8e93b45

### Expected behavior:
The scan should succeed with all possible facts combination.

### Actual behavior:
Some combination make the command to fail and no return a proper exit code.

### Steps to reproduce:
Create a credential and profile and scan passing the following facts:

```console
rho scan -vvvv --profile <profile_name> --facts "cpu.cpu_family" "cpu.model_name" "date.filesystem_create" "jboss.installed-versions" "systemid.system_id" "dmi.processor-family" "uname.kernel" "uname.hostname" "etc_release.release" "cpu.count" "connection.host" "connection.port" "connection.uuid" --reportfile report.csv --logfile scan.log
```

After running the above command, it exits with a 0 exit code but checking the generated log there is the following message:

```
TASK [etc_release : gather etc_release.release based on redhat_release_found_release] ***
task path: /home/elyezer/code/rho/roles/etc_release/tasks/main.yml:141
fatal: [127.0.0.1]: FAILED! => {
    "failed": true,
    "msg": "The conditional check '\"etc_release.release\" in facts_to_collect and redhat_release_found[\"stdout_lines\"][0] == \"Y\"' failed. The error was: error while evaluating conditional (\"etc_release.release\" in facts_to_collect and redhat_release_found[\"stdout_lines\"][0] == \"Y\"): 'dict object' has no attribute 'stdout_lines'\n\nThe error appears to have been in '/home/elyezer/code/rho/roles/etc_release/tasks/main.yml': line 141, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: gather etc_release.release based on redhat_release_found_release\n  ^ here\n"
}
```

It seems that the tasks are not atomic and some may rely on others running in order to have the proper information.

### Environment information:
Both the scan controller and target are a bare metal Fedora 26 system, actually they are the same system.

**Comment by chambridge** [comment]
reviewing this it looks like this potential issue is likely limited to the following two roles:

- etc_release
- virt
