### ISSUE TITLE
etc-issue fact output includes failed string interpolation

### ISSUE THREAD

**Issue by kdelee** [quipucords/rho#320]
# Openning a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Low
___

## Description:

The `etc-issue.etc-issue` fact contains what looks like a failed string interpolation.

| etc-issue.etc-issue | etc_release.version |
| --------------- | ---------------- |
| Red Hat Enterprise Linux Server release 5.9 (Tikanga)Kernel \r on an \m | 5.9 (Tikanga) |
| \SKernel \r on an \m | 7.4 (Maipo) |
| Red Hat Enterprise Linux Server release 6.9 (Santiago)Kernel \r on an \m | 6.9 (Santiago) |

___

### Version of rho:
e175251bffd2e734230ea857b4af3fc488a2dc0a

### Expected behavior:
Output should not include failed interpolation

### Actual behavior:
Output does include buggy output.

### Steps to reproduce:
Scan a RHEL machine.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora             | 25        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | --          | VCenter
Target System   | RHEL             | 7.4        | --          | VCenter
Target System   | RHEL             | 6.9        | --          | VCenter

**Comment by chambridge** [comment]
We are just collecting the contents of a file:
https://github.com/quipucords/rho/blob/master/roles/file_contents/tasks/main.yml#L8

This is the actual contents of a file:
```
[root@ef43deab8f65 /]# cat /etc/issue
\S
Kernel \r on an \m
```

Don't know why that is the contents, but we're collecting it.

I'm going to close this out. Feel free to reopen if there is further reasoning here.

**Comment by kdelee** [comment]
Ah, ok. Thanks for the clarification.
