### ISSUE TITLE
No output is shown during the ping phase

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#326]
# Openning a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
No results are shown from the ping phase when mapping auths to hosts. I think we should at least show a status message letting the user know that's what's happening because in a large environment this could take a long time and with no output the user might believe the script is hung. Maybe a similar approach to the regular output where it is dependent on the verbosity level but it at least always shows something to let the user know work is being done. 
___

**Comment by chambridge** [comment]
https://github.com/quipucords/rho/issues/302
