### ISSUE TITLE
Unit test improvements

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#33]
Currently unit tests are dependent on several factors that they should be decoupled from:

- [x] pre-existence of files like `data/profiles`, `data/credential`
- [x] input via getpass routine
- [x] ordering of test -- clear all commands break other tests that depend on files mentioned above

Need to decouple ordering of test from each test case. Each test should create and teardown as necessary.

Need to separate input code and I/O code and just functions input and returns.

**Comment by chambridge** [comment]
We should focus on improving the unit testing of the commands under the `rho` module only for now. We may be rewriting those commands under `module_utils` to be raw tasks similar to the JBossScanner, so let's not waste cycles writing unit tests for code we may be greatly changing.

**Comment by omaciel** [comment]
I wonder if this [method](https://github.com/omaciel/fauxfactory/blob/master/fauxfactory/factories/systems.py#L169) from [FauxFactory](https://github.com/omaciel/fauxfactory) would be helpful to your tests around facts?
