### ISSUE TITLE
cpu.cores Does not Always properly Account for Hyperthreading

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#355]
# Openning a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
For some earlier version of RHEL the number of CPU cores determined by the cpu.cores fact is 2x the number of physical cores due to hyperthreading. 

The bolded part of the command below shows when cpu.cores is not found in /proc/cpuinfo we just count the number of time "processor" appears in /proc/cpuinfo which is equivalent to logical CPUs which include hyperthreading. 

CPU_CORES=$(grep cpu.cores /proc/cpuinfo | sed 's/cpu.*:.\?//g' | sort -u); **if [ -z "$CPU_CORES" ]; then CPU_CORES=$(grep processor /proc/cpuinfo | wc -l);** else CPU_SOCKETS=$(grep "physical id" /proc/cpuinfo | sort -u| wc -l); let CPU_CORES=CPU_CORES\*CPU_SOCKETS; fi; echo "$CPU_CORES" | sed 's/\s*//g' 

___

### Version of rho:
0.28

### Expected behavior:
Should check if hyperthreading is enabled and if the cpu.cores is not found in /proc/cpuinfo then divide CPU cores by 2. 

Use the following to check if hyperthreading is enabled. 
number of siblings = 2 * number of cores per socket
cat /proc/cpuinfo |egrep 'sibling|cores' 

### Steps to reproduce:
Run against system with kernel 2.6.18-419.el5. 

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Target System   | RHEL             | 2.6.18-419.el5

**Comment by mdvickst** [comment]
Uploading example outputs of servers where cpu cores from jboss task and from cpu.cpus was reported to be 2x number of physical cores. 
[server1_exmaple.txt](https://github.com/quipucords/rho/files/1383018/server1_exmaple.txt)
[server2_example.txt](https://github.com/quipucords/rho/files/1383019/server2_example.txt)

**Comment by chambridge** [comment]
@mdvickst I'm not sure if this is something that was put in `rho` before the *ansible; 2.0* branch was created, but I'm not sure what cpu.cores logic you are pointing to. We have 'cpu.count', and 'subman.cpu.cpu_socket(s)', 'subman.cpu.core(s)_per_socket'. Seems more like we don't have this feature today in the current version of rho and it needs to be added. I just want to clarify.

**Comment by mdvickst** [comment]
Sorry I was referring to cpu.count. Maybe we should change cpu.count to be cpu.core_count since we already have cpu.socket_count or just add a separate cpu.core_count since the cores can differ from the number of logical cpus if hyperthreading is enabled. 

I believe the command for cpu.count right now is the same as the if condition in the old cpu.cores where we are just counting logical CPUs (which will be 2x the number of cores if hyperthreading is enabled). 

cat /proc/cpuinfo | grep '^processor\s*.' | wc -l

**Comment by chambridge** [comment]
Currently we have the following tasks:
```
- name: gather cpu.count fact
  raw: cat /proc/cpuinfo | grep '^processor\s*.' | wc -l
  register: cpu_count
```

```
- name: gather cpu.socket_count fact
  raw: /usr/sbin/dmidecode -t 4 | grep 'Socket Designation'| wc -l
  register: cpu_socket_count
```

Based on your above if feel like it suggest we should/could be getting socket count by doing the following:
```
grep "physical id" /proc/cpuinfo | sort -u| wc -l
```
1) should I update the above task get socket count from `/proc/cpuinfo`? (especially as dmidecode requires sudo)
2) If I do (1) should I move the above dmidecode command for socket_count to the dmi role so we can get it from there in addition to `/proc/cpuinfo`?
3) should I add a new fact round `cpu.hyperthreading_enabled` that uses `cat /proc/cpuinfo |egrep 'sibling|cores'`, along with a new `cpu.core_count`?

**Comment by mdvickst** [comment]
I think based on this [article](https://access.redhat.com/solutions/61791) the dmidecode method is still more accurate (I believe it correctly determines if a socket is not populated and does not report it) but requires sudo/root. 

Since it would still be good to collect CPU information if sudo/root is not accessible I think the ideal solution for socket count is 1 fact which uses the dmidecode method if using root or sudo then falls back to cpuinfo if not. 

I think adding a fact for hyperthreading would be helpful and then that can be used in the determination of cpu.core_count. 

Using the existing core count fact from the jboss scanner I think hyperthreading should be used to divide core count by 2 if using the "grep processor /proc/cpuinfo | wc -l" method

Sample logic for CPU Cores
- get # of cores per socket from /proc/cpuinfo - grep cpu.cores /proc/cpuinfo | sed 's/cpu.:.?//g' | sort -u
- If that command is not successful (meaning older version of RHEL) then collect # of logical cpus using - grep processor /proc/cpuinfo | wc -l)
  ** If hyperthreading is enabled divide that number by 2 and return it
  ** else return # of logical cpus
- else cpu cores is equal to # of cores per socket times the number of CPU sockets (determined by above logic/fact)

**Comment by chambridge** [comment]
Some comments against last PR. reopening to fix.
