### ISSUE TITLE
Make fact definition more robust

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#374]
We could make it impossible to cause #373 again by having a fact-defining function that automatically adds a fact to the right lists. I.e. instead of
```
MY_TUPLE = ('my-new-fact')
...
OTHER_TUPLE = ... + MY_TUPLE
```

it should be

```
new_fact('my-new-fact', categories=[SENSITIVE_FACTS, GREEN_FACTS])
```

`new_fact` would add facts to `ALL_FACTS` automatically.

**Comment by elyezer** [comment]
I think the function should also accept the help message so the `rho fact list` is updated automatically when a new fact is added, this will prevent bugs like #387 by having a central and unique place to consult for fact information.
