### ISSUE TITLE
Refactor rho commands

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#38]
Currently all of the rho commands exist in a single file, `rho/clicommands`.
For improved maintainability lets look to split the separate commands (classes) out into their own files.

Additionally to improve unit testing capabilities we should extract out I/O (file writing / reading) so that we can test the "strings" that we expect to be put into files or test the reaction of code to strings that we would expect to come from files.

**Comment by noahl** [comment]
Assigning myself since I've been working on this issue. However, I will be out for the next week, so I understand that someone else may need to take it.

**Comment by chambridge** [comment]
https://github.com/quipucords/rho/pull/49
https://github.com/quipucords/rho/pull/52
https://github.com/quipucords/rho/pull/58

Above PRs are all related to separating out the large files into maintainable classes or utilities.

Work still remains to handle the I/O separation to improve unit test capabilities.

**Comment by chambridge** [comment]
@noahl Any other items you want to focus on here in terms of refactor? I would like to programmatically call Ansible instead of using pexpect, but I will open another issue for that as its a larger work item. If no, then I think we can close this out as I feel the code is in much better shape.

**Comment by noahl** [comment]
@chambridge closing this sounds good to me. I don't have anything else on my mind right now, and I can always open another issue as you said.
