### ISSUE TITLE
Check for common JBoss files

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#395]
Add the ability to check for files commonly associated with jboss, in addition to directories. Then add the following, from @mdvickst in https://github.com/quipucords/rho/pull/370#issuecomment-336974439 : 

/opt/deploy/jboss/jbossas6/jboss-modules.jar;
/usr/share/java/jboss-modules.jar;
/usr/share/jbossas/jboss-modules.jar;

**Comment by chambridge** [comment]
https://github.com/quipucords/rho/pull/410
