### ISSUE TITLE
Report Generation Does no Complete

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#414]
# Openning a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High

___

## Description:
Customer is running scan and they get the following error during the report generation. 
TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [write : store facts from all hosts in a variable] ************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "|combine expects dictionaries, got Undefined"}
	to retry, use: --limit @/usr/share/ansible/rho/rho_playbook.retry
___

### Version of rho:
0.28

### Expected behavior:
Correctly generate a report

### Actual behavior:
fails on localhost 

### Steps to reproduce:
List clear steps to reproduce the bug.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by chambridge** [comment]
**An issue found:**
7 Systems are Solaris. Fatal error encountered for these 7 systems when we split on 'release' and select the second value from that split, but 'release' isn't in the output.

`Solaris 9 8/03 s9s_u4wos_08a SPARC`

**Comment by chambridge** [comment]
We were able to complete the scan after a few updates. Closing out this issue.
