### ISSUE TITLE
jboss.eap.init-files is not included when performing a scan with --facts jboss

### ISSUE THREAD

**Issue by elyezer** [quipucords/rho#466]
## Specify type:
- Bug

### Bug severity (if applicable):
- Medium
___

## Description:
The fact `jboss.eap.init-files` should be present on the report when performing a scan with `--facts jboss`.
___

### Version of rho:
0.30 (latest master fbd4a6d32ea95401c7816f03371648e57a39d14a)

### Expected behavior:
The fact jboss.eap.init-files should be present on the report.

### Actual behavior:
The fact jboss.eap.init-files is not present on the report.

### Steps to reproduce:
Make sure you have an auth and profile ready to scan a system. Perform a scan by running `rho scan --profile <profile> --facts jboss --reportfile report.csv`

### Environment information:
This happens for all tested environments, both RHEL and Fedora as target systems.

**Comment by noahl** [comment]
Closed by #470 .
