### ISSUE TITLE
Merge changes from 'master' into 'rho-2.0'

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#5]
Sadly, the branches have diverged!

`git log remotes/origin/rho-2.0..remotes/origin/master` (in a local checkout) shows the work to do. It doesn't look too bad.

**Comment by noahl** [comment]
The commits to be merged:
- [x] cd1f0e
- [x] a030dd
- [x] ff9fe8
- [x] ffadb6
- [x] 1ed55d
- [x] 732f57
- [x] f38d07
- [x] cf7ff7
- [x] 641c68
- [x] f2984d
- [x] d229f4
- [x] 035927
- [x] e95fe0

**Comment by chambridge** [comment]
I merged your pull request. 
Assuming that is everything, the final step here is branch renaming; then we can close this issue out.
