### ISSUE TITLE
Better support for Ubuntu in EtcReleaseRhoCmd

### ISSUE THREAD

**Issue by noahl** [quipucords/rho#51]
`etc_release_command.py` line 41 assumes that having `/etc/debian-version` present means the OS is Debian. Could it be Ubuntu too?

This issue was previously a FIXME in that file.

**Comment by chambridge** [comment]
Let's defer this issue as the focus of the tool doesn't really depend on distinguishing between Debian and Ubuntu. We can reopen or revisit if this becomes of higher importance in the future.
