### ISSUE TITLE
jboss.eap.summary fact not available in latest from copr

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#516]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- High
___

## Description:
I may be doing something wrong but I installed rho-0.0.31-1.git.103.f0b0609.el7.centos.noarch and the jboss.eap.summary fact is not listed in facts or in the output. 

[root@mvickstr-rhel7 ~]# cat dot31-2.csv | grep summary
[root@mvickstr-rhel7 ~]# rho fact list | grep summary
___

### Version of rho:
 0.0.31

### Expected behavior:
Describe the expected behavior for the program.

### Actual behavior:
Provide the actual behavior for the program.

### Steps to reproduce:
List clear steps to reproduce the bug.

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | RHEL             | 7.4        | 3.6            | Bare Metal
Target System   | RHEL             | 5.9        | 2.4.6          | RHEV

**Comment by chambridge** [comment]
@noahl  Did the summary fact work in the `dev` branch; COPR builds the `master` branch. This needs to be merged into master. Assigning this to Noah to resolve.
