### ISSUE TITLE
Remove redhat.package.buildhost

### ISSUE THREAD

**Issue by mdvickst** [quipucords/rho#544]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- High

___

## Description:
Remove the redhat.package.buildhost facts from the default scan that way the memory required to gather facts is less. These facts are essentially duplicates of the redhat.package.gpg facts.

**Comment by noahl** [comment]
My conversation with Mark was that we should actually remove these packages:
redhat-packages.is_redhat - determines if package is a Red Hat package
redhat-packages.last_installed - last installed package
redhat-packages.last_built - last built package
redhat-packages.num_rh_packages - number of Red Hat packages
redhat-packages.num_installed_packages - number of installed packages

they are duplicates of these which we should keep:
redhat-packages.gpg.is_redhat - determines if package is a Red Hat package filtered by GPG keys
redhat-packages.gpg.last_installed - last installed package filtered by GPG keys
redhat-packages.gpg.last_built - last built package filtered by GPG keys
redhat-packages.gpg.num_rh_packages - number of Red Hat packages filtered by GPG keys
redhat-packages.gpg.num_installed_packages - number of installed packages filtered by GPG keys
