### ISSUE TITLE
Add ClientAlive options to discovery and host flows

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#550]
## Specify type:
- Enhancement

## Description:
Update the ssh-comman-args

Discovery:
https://github.com/quipucords/rho/blob/master/rho/host_discovery.py#L121
`--ssh-common-args="-o ServerAliveInterval=10 ClientAliveInterval=120 ClientAliveCountMax=0"`

Host Scan:
https://github.com/quipucords/rho/blob/master/rho_playbook.yml#L10
`ansible_ssh_common_args: '-o ServerAliveInterval=10 ClientAliveInterval=600 ClientAliveCountMax=0'`

**Comment by noahl** [comment]
Unfortunately it looks like `ClientAliveInterval` and `ClientAliveCountMax` are only sshd configuration options, not ssh options. Unless the user has already configured sshd with these options on their remote machines, we can't use them.

See https://linux.die.net/man/5/ssh_config and https://linux.die.net/man/5/sshd_config .

**Comment by noahl** [comment]
`ServerAliveCountMax` is a thing on the client side, but I'm not sure if it will be helpful here.

**Comment by chambridge** [comment]
Let's close this out then. Nothing to do.
