### ISSUE TITLE
Ansible Update

### ISSUE THREAD

**Issue by benneteapen** [quipucords/rho#599]
Is RHO being updated anymore ? When running RHO, an error message like "All auths are invalid for this profile" is what I always get. The ping log looks like this : 10.1.11.13 | CHANGED | rc=0. I figured Ansible changed their output from SUCCESS to CHANGED and now Rho is not recognizing this. The temporary fix is to modify the host_discovery.py file but is that the only solution as of now ?

**Comment by chambridge** [comment]
No, RHO is no longer being updated. Work was transitioned to the following repositories which capture all of the function in RHO and has provided more features:
https://github.com/quipucords/quipucords
https://github.com/quipucords/qpc
https://github.com/quipucords/quipucords-ui
