### ISSUE TITLE
Establish test bed environment

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#6]
Setup a set of systems to enable initial testing and demo of existing `rho-2.0` functionality.

- Small number of systems to start (2 - 5).
- Focus on a "green path" range of RHEL version support (RHEL 6 & 7).

**Comment by elyezer** [comment]
The initial test bed environment will be like the following:

- [x] Jenkins master
- [x] OpenStack project to provide nodes to Jenkins
- [x] Nodepool setup
- [x] Base nodepool image creation for RHEL 7
- [x] Base nodepool image creation for CentOS 7
- [x] Base nodepool image creation for Fedora 25

With the above environment in place we can create jobs that will use one node and then verify if RHO 2.0 is able to gather the expected information for that system.

**Comment by elyezer** [comment]
We decided to have nodepool only provisioning Jenkins' slaves. The machines to target during the scan will be created on VCenter.

That said this issue can be closed and additional will be created if we decide to add more images or systems to the permutation matrix.
