### ISSUE TITLE
Change ansbile RHEL fact gathering modules to use raw tasks in a role instead of having python scripts

### ISSUE THREAD

**Issue by chambridge** [quipucords/rho#68]
We currently collect a range of facts via Ansible modules (python scripts -- e.g. https://github.com/quipucords/rho/blob/master/module_utils/redhat_release_command.py#L30) that run on the remote server.

Due to dependency on Python levels needed on the scanned endpoints this may not be feasible. We may need to convert our existing modules to run as raw tasks as is done in the JBoss Scanner see the following example:
https://github.com/mdvickst/jboss-scanner/blob/master/roles/collect_jboss_raw/tasks/main.yml#L5

- [x] uname.*
- [x] date.*
- [x] redhat-release.*
- [x] instnum.*
- [x] systemid.*
- [x] cpu.*
- [x] etc_release.*
- [x] etc-issue.*
- [x] dmi.*
- [x] virt.*
- [x] redhat-packages.*
- [x] subman.*
- [x] virt-what.*

**Comment by chambridge** [comment]
@j00bar @mdvickst

Feel free to comment. We had previously mentioned this option or creating a binary that would be sent and run.

**Comment by j00bar** [comment]
Yep. Each Ansible module has a payload that it drops on the target system, I believe charmingly called AnsiBallz. For all stock *nix modules except `raw`, this payload is Python, but it can be in any language out there. The only realistic options that would allow that portability would be Bash or statically compiled languages like Go.

**Comment by mdvickst** [comment]
One strategy might be to use a conditional for OS versions that don't meet Ansible's minimum requirements for Python and revert back to a subset of facts collected via an alternative method. Right now I believe the JBoss scanner  looks for devices that "fail" the ping module but Ansible was still able to log in to. https://github.com/mdvickst/jboss-scanner/blob/master/build_ansible.py#L249

I'm not sure if Rho 2.0 does this or not.

**Comment by chambridge** [comment]
All individual scripts have been converted to raw tasks. This issue will be used for the remainder of the clean up.
- removal of the `module_utils` folder
- removal of `library/run_cmds.py`
- removal of the *collect* role
- capture of connection data external to `run_cmds.py`
